name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['!v*']

env:
  # renovate: datasource=npm depName=corepack
  COREPACK_VERSION: 0.31.0
  # renovate: datasource=node-version depName=node
  NODE_VERSION: 22.13.1

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable corepack
        run: |
          npm install -g corepack@${COREPACK_VERSION}
          corepack enable
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format check
        run: pnpm format-check
      - name: Lint
        run: pnpm lint
      # - name: Test
      #   run: pnpm test --ci --coverage
